name: Deploy Static Site to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # No build step needed (since files are pre-built)
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # ⚠️ Must match your folder
          publish_branch: gh-pages
          force_orphan: true  # Delete old files
          keep_files: false   # Ensure ONLY `./out` files are deployed
